apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .Values.postgresPushSecret.secretStore.name }}
  namespace: {{ .Values.team }}-{{ .Values.environment }}
spec:
  deletionPolicy: Delete # the provider' secret will be deleted if the postgresPushSecret is deleted
  refreshInterval: 1h0m0s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: {{ .Values.postgresPushSecret.secretStore.storeRef}}
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ .Values.postgresPushSecret.secretStore.name }}
  data:
    - match:
        remoteRef:
          remoteKey: {{ .Values.postgresPushSecret.secretStore.name }}