kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.team }}-{{ .Values.environment }}
  labels: {{ .Values.labels | toYamlPretty | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'

spec:
  teamId: {{ .Values.team }}
{{- with .Values.postgresql }}
  postgresql:
    version: "{{ .version }}"
  numberOfInstances: {{ .replicas }}
  enableConnectionPooler: {{ .enableConnectionPooler }}
  enableReplicaConnectionPooler: {{ .enableReplicaConnectionPooler }}
  volume: {{ .volume | toYamlPretty | nindent 4 }}
  users: {{ .users | toYamlPretty | nindent 4 }}
  databases: {{ .databases | toYamlPretty | nindent 4 }}
  resources: {{ .resources | toYamlPretty | nindent 4 }}
{{- end }}