team: data
environment: prod
labels:
  app: data
  component: redis
  env: prod
  team: data
aws:
  accountId: "632988741882"
  region: us-east-1
redisExternalSecret:
  name: redis-secret
  storeRef: prod-cluster-secret-store-secrets-manager ##Secret Store Ref to use